In [15]:
import numpy as np

In [23]:
arr1 = np.array([
    [ 5,  1,  3,  2,  4,  6],
    [ 5,  8,  0,  3,  1,  2],
    [ 3, 10,  6, 21, 15,  1]  
])
print(arr1)

[[ 5  1  3  2  4  6]
 [ 5  8  0  3  1  2]
 [ 3 10  6 21 15  1]]


In [24]:
arr1.shape  # it's 3 rows, 6 columns

(3, 6)

In [25]:
arr1.ndim  # it's 2D

2

#### For every row (`axis=1`)  
#### delete the third item in that row (_index = 2_)

In [26]:
arr2 = np.delete(x, 2, axis=1)
print(arr1)
print()
print(arr2)

[[ 5  1  3  2  4  6]
 [ 5  8  0  3  1  2]
 [ 3 10  6 21 15  1]]

[[ 5  1  2  4  6]
 [ 5  8  3  1  2]
 [ 3 10 21 15  1]]
